import React from 'react';
import { ElectronicsIcon } from '../components/icons/ElectronicsIcon';
import { CarIcon } from '../components/icons/CarIcon';
import { HouseIcon } from '../components/icons/HouseIcon';
import { FashionIcon } from '../components/icons/FashionIcon';
import { PlantIcon } from '../components/icons/PlantIcon';
import { HobbiesIcon } from '../components/icons/HobbiesIcon';
import { MarketplaceIcon } from '../components/icons/MarketplaceIcon';
import { TourismIcon } from '../components/icons/TourismIcon';
import { HealthcareIcon } from '../components/icons/HealthcareIcon';
import { EducationIcon } from '../components/icons/EducationIcon';
import { ServicesIcon } from '../components/icons/ServicesIcon';
import { RetailIcon } from '../components/icons/RetailIcon';
import { DefaultCategoryIcon } from '../components/icons/DefaultCategoryIcon';

export const MAZDADY_CATEGORIES = {
    "Marketplaces": {
      "Vehicles": {
          "Cars": [
              { name: "Abarth", flag: "IT" },
              { name: "Abbott-Detroit", flag: "US" },
              { name: "AC Cars", flag: "GB" },
              { name: "Acura", flag: "JP" },
              { name: "Adler", flag: "DE" },
              { name: "AEG", flag: "DE" },
              { name: "Aerocar", flag: "US" },
              { name: "AGM", flag: "CN" },
              { name: "Agrale", flag: "BR" },
              { name: "Aion", flag: "CN" },
              { name: "Aixam", flag: "FR" },
              { name: "AJS", flag: "GB" },
              { name: "Alfa Romeo", flag: "IT" },
              { name: "Alpina", flag: "DE" },
              { name: "Alpine", flag: "FR" },
              { name: "Alvis", flag: "GB" },
              { name: "AM General", flag: "US" },
              { name: "American Motors (AMC)", flag: "US" },
              { name: "Ampere", flag: "IN" },
              { name: "Amphicar", flag: "DE" },
              { name: "Aptera", flag: "US" },
              { name: "Arash", flag: "GB" },
              { name: "Arcimoto", flag: "US" },
              { name: "Ariel", flag: "GB" },
              { name: "Armstrong Siddeley", flag: "GB" },
              { name: "Arrinerra", flag: "PL" },
              { name: "Artega", flag: "DE" },
              { name: "Ascari", flag: "GB" },
              { name: "Ashok Leyland", flag: "IN" },
              { name: "Asia Motors", flag: "KR" },
              { name: "Aston Martin", flag: "GB" },
              { name: "Atalanta", flag: "GB" },
              { name: "Atul Auto", flag: "IN" },
              { name: "Auburn", flag: "US" },
              { name: "Audi", flag: "DE" },
              { name: "Austin", flag: "GB" },
              { name: "Austin-Healey", flag: "GB" },
              { name: "Autobianchi", flag: "IT" },
              { name: "AutoVAZ (Lada)", flag: "RU" },
              { name: "Avanti", flag: "US" },
              { name: "BAIC", flag: "CN" },
              { name: "Bajaj", flag: "IN" },
              { name: "Baojun", flag: "CN" },
              { name: "BAW", flag: "CN" },
              { name: "Beaufort", flag: "DE" },
              { name: "Bentley", flag: "GB" },
              { name: "Berkeley", flag: "GB" },
              { name: "Berliet", flag: "FR" },
              { name: "Bertone", flag: "IT" },
              { name: "Bestune", flag: "CN" },
              { name: "Bitter", flag: "DE" },
              { name: "Bizzarrini", flag: "IT" },
              { name: "BLAC", flag: "CN" },
              { name: "Blackwell", flag: "US" },
              { name: "BMC", flag: "GB" },
              { name: "BMW", flag: "DE" },
              { name: "Bollinger", flag: "US" },
              { name: "Borgward", flag: "DE" },
              { name: "Brabus", flag: "DE" },
              { name: "Brammo", flag: "US" },
              { name: "Breda", flag: "IT" },
              { name: "Brilliance", flag: "CN" },
              { name: "Bristol", flag: "GB" },
              { name: "Brooke", flag: "GB" },
              { name: "Brush", flag: "US" },
              { name: "Brutsch", flag: "DE" },
              { name: "Bufori", flag: "MY" },
              { name: "Bugatti", flag: "FR" },
              { name: "Buick", flag: "US" },
              { name: "BYD", flag: "CN" },
              { name: "Cadillac", flag: "US" },
              { name: "Canoo", flag: "US" },
              { name: "Caparo", flag: "GB" },
              { name: "Caresto", flag: "SE" },
              { name: "Caterham", flag: "GB" },
              { name: "Caterpillar", flag: "US" },
              { name: "Changan", flag: "CN" },
              { name: "Changhe", flag: "CN" },
              { name: "Checker", flag: "US" },
              { name: "Chery", flag: "CN" },
              { name: "Chevrolet", flag: "US" },
              { name: "Chrysler", flag: "US" },
              { name: "Citroën", flag: "FR" },
              { name: "Cizeta", flag: "IT" },
              { name: "Cole", flag: "US" },
              { name: "Commer", flag: "GB" },
              { name: "Connaught", flag: "GB" },
              { name: "Cord", flag: "US" },
              { name: "Corvette", flag: "US" },
              { name: "Crosley", flag: "US" },
              { name: "CUPRA", flag: "ES" },
              { name: "Czinger", flag: "US" },
              { name: "Dacia", flag: "RO" },
              { name: "Dadi", flag: "CN" },
              { name: "Daf", flag: "NL" },
              { name: "Daihatsu", flag: "JP" },
              { name: "Daimler", flag: "GB" },
              { name: "Datsun", flag: "JP" },
              { name: "Daewoo", flag: "KR" },
              { name: "David Brown", flag: "GB" },
              { name: "Dayun", flag: "CN" },
              { name: "De Dion-Bouton", flag: "FR" },
              { name: "De Tomaso", flag: "IT" },
              { name: "Deepal", flag: "CN" },
              { name: "DeLorean", flag: "US" },
              { name: "Denza", flag: "CN" },
              { name: "Derways", flag: "RU" },
              { name: "DeSoto", flag: "US" },
              { name: "Detroit Electric", flag: "US" },
              { name: "Devaux", flag: "AU" },
              { name: "Devon", flag: "US" },
              { name: "DKW", flag: "DE" },
              { name: "Dodge", flag: "US" },
              { name: "Dongfeng", flag: "CN" },
              { name: "Donkervoort", flag: "NL" },
              { name: "Doretti", flag: "GB" },
              { name: "Dort", flag: "US" },
              { name: "DS Automobiles", flag: "FR" },
              { name: "Duesenberg", flag: "US" },
              { name: "Durant", flag: "US" },
              { name: "Eagle", flag: "US" },
              { name: "Edsel", flag: "US" },
              { name: "Eicher", flag: "IN" },
              { name: "Elaris", flag: "DE" },
              { name: "Elemental", flag: "GB" },
              { name: "Elfin", flag: "AU" },
              { name: "Elva", flag: "GB" },
              { name: "Enfield", flag: "IN" },
              { name: "Englon", flag: "CN" },
              { name: "Eterniti", flag: "GB" },
              { name: "Exeed", flag: "CN" },
              { name: "Facel Vega", flag: "FR" },
              { name: "Farbio", flag: "GB" },
              { name: "Faraday Future", flag: "US" },
              { name: "Fargo", flag: "US" },
              { name: "FAW", flag: "CN" },
              { name: "Ferrari", flag: "IT" },
              { name: "Fiat", flag: "IT" },
              { name: "Fisker", flag: "US" },
              { name: "Flint", flag: "US" },
              { name: "Force Motors", flag: "IN" },
              { name: "Ford", flag: "US" },
              { name: "Fornasari", flag: "IT" },
              { name: "Foton", flag: "CN" },
              { name: "Franklin", flag: "US" },
              { name: "Frazer Nash", flag: "GB" },
              { name: "FSO", flag: "PL" },
              { name: "GAC Motor", flag: "CN" },
              { name: "Gardner Douglas", flag: "GB" },
              { name: "GAZ", flag: "RU" },
              { name: "Geely", flag: "CN" },
              { name: "Genesis", flag: "KR" },
              { name: "Geo", flag: "US" },
              { name: "Gillet", flag: "BE" },
              { name: "Ginetta", flag: "GB" },
              { name: "GMC", flag: "US" },
              { name: "Gonow", flag: "CN" },
              { name: "Gordon-Keeble", flag: "GB" },
              { name: "Graham-Paige", flag: "US" },
              { name: "Great Wall", flag: "CN" },
              { name: "Grecav", flag: "IT" },
              { name: "Grinnall", flag: "GB" },
              { name: "Gumpert", flag: "DE" },
              { name: "Hafei", flag: "CN" },
              { name: "Haima", flag: "CN" },
              { name: "Haval", flag: "CN" },
              { name: "Healey", flag: "GB" },
              { name: "Hennessey", flag: "US" },
              { name: "Hillman", flag: "GB" },
              { name: "Hindustan", flag: "IN" },
              { name: "HiPhi", flag: "CN" },
              { name: "Hispano-Suiza", flag: "ES" },
              { name: "Holden", flag: "AU" },
              { name: "Honda", flag: "JP" },
              { name: "Hongqi", flag: "CN" },
              { name: "Horch", flag: "DE" },
              { name: "Hotchkiss", flag: "FR" },
              { name: "HRG", flag: "GB" },
              { name: "Hudson", flag: "US" },
              { name: "Humber", flag: "GB" },
              { name: "Hummer", flag: "US" },
              { name: "Hupmobile", flag: "US" },
              { name: "Hyundai", flag: "KR" },
              { name: "ICML", flag: "IN" },
              { name: "IKCO", flag: "IR" },
              { name: "Infiniti", flag: "JP" },
              { name: "Innocenti", flag: "IT" },
              { name: "Intermeccanica", flag: "IT" },
              { name: "International Harvester", flag: "US" },
              { name: "Invicta", flag: "GB" },
              { name: "Isdera", flag: "DE" },
              { name: "Iso", flag: "IT" },
              { name: "Isuzu", flag: "JP" },
              { name: "Italdesign", flag: "IT" },
              { name: "Iveco", flag: "IT" },
              { name: "JAC Motors", flag: "CN" },
              { name: "Jaguar", flag: "GB" },
              { name: "Jawa", flag: "CZ" },
              { name: "Jeep", flag: "US" },
              { name: "Jensen", flag: "GB" },
              { name: "Jetour", flag: "CN" },
              { name: "Jetta", flag: "CN" },
              { name: "Jinbei", flag: "CN" },
              { name: "Jowett", flag: "GB" },
              { name: "Kaiser", flag: "US" },
              { name: "Karma", flag: "US" },
              { name: "Karrier", flag: "GB" },
              { name: "Kia", flag: "KR" },
              { name: "Koenigsegg", flag: "SE" },
              { name: "KTM", flag: "AT" },
              { name: "Lada", flag: "RU" },
              { name: "Lagonda", flag: "GB" },
              { name: "Lamborghini", flag: "IT" },
              { name: "Lanchester", flag: "GB" },
              { name: "Lancia", flag: "IT" },
              { name: "Land Rover", flag: "GB" },
              { name: "Landwind", flag: "CN" },
              { name: "Laraki", flag: "MA" },
              { name: "LaSalle", flag: "US" },
              { name: "Lea-Francis", flag: "GB" },
              { name: "Leapmotor", flag: "CN" },
              { name: "Lexus", flag: "JP" },
              { name: "Leyland", flag: "GB" },
              { name: "Li Auto", flag: "CN" },
              { name: "Lifan", flag: "CN" },
              { name: "Ligier", flag: "FR" },
              { name: "Lincoln", flag: "US" },
              { name: "Lister", flag: "GB" },
              { name: "Lloyd", flag: "DE" },
              { name: "Lobini", flag: "BR" },
              { name: "Locomobile", flag: "US" },
              { name: "Lordstown", flag: "US" },
              { name: "Lotus", flag: "GB" },
              { name: "Lucid", flag: "US" },
              { name: "Luxgen", flag: "TW" },
              { name: "Lynk & Co", flag: "CN" },
              { name: "Mahindra", flag: "IN" },
              { name: "Manta", flag: "US" },
              { name: "Marcos", flag: "GB" },
              { name: "Marlin", flag: "GB" },
              { name: "Marmon", flag: "US" },
              { name: "Maruti Suzuki", flag: "IN" },
              { name: "Maserati", flag: "IT" },
              { name: "Maxus", flag: "CN" },
              { name: "Maybach", flag: "DE" },
              { name: "Mazda", flag: "JP" },
              { name: "Mazzanti", flag: "IT" },
              { name: "McLaren", flag: "GB" },
              { name: "Melkus", flag: "DE" },
              { name: "Mercedes-Benz", flag: "DE" },
              { name: "Mercury", flag: "US" },
              { name: "Merkur", flag: "US" },
              { name: "Messerschmitt", flag: "DE" },
              { name: "MG", flag: "GB" },
              { name: "Micro", flag: "CH" },
              { name: "Mini", flag: "GB" },
              { name: "Mitsubishi", flag: "JP" },
              { name: "Mitsuoka", flag: "JP" },
              { name: "Mobius", flag: "KE" },
              { name: "Monteverdi", flag: "CH" },
              { name: "Morgan", flag: "GB" },
              { name: "Morris", flag: "GB" },
              { name: "Mosler", flag: "US" },
              { name: "Nami", flag: "CN" },
              { name: "Napier", flag: "GB" },
              { name: "Nash", flag: "US" },
              { name: "Neta", flag: "CN" },
              { name: "Neuron", flag: "US" },
              { name: "Nikola", flag: "US" },
              { name: "NIO", flag: "CN" },
              { name: "Nissan", flag: "JP" },
              { name: "Noble", flag: "GB" },
              { name: "NSU", flag: "DE" },
              { name: "Oakland", flag: "US" },
              { name: "Oldsmobile", flag: "US" },
              { name: "Oltcit", flag: "RO" },
              { name: "Onvo", flag: "CN" },
              { name: "Opel", flag: "DE" },
              { "name": "Ora", "flag": "CN" },
              { name: "Osca", flag: "IT" },
              { name: "Overland", flag: "US" },
              { name: "Packard", flag: "US" },
              { name: "Pagani", flag: "IT" },
              { name: "Panhard", flag: "FR" },
              { name: "Panoz", flag: "US" },
              { name: "Panther", flag: "GB" },
              { name: "Peerless", flag: "GB" },
              { name: "Pegaso", flag: "ES" },
              { name: "Perana", flag: "ZA" },
              { name: "Peugeot", flag: "FR" },
              { name: "Pierce-Arrow", flag: "US" },
              { name: "Pininfarina", flag: "IT" },
              { name: "Plymouth", flag: "US" },
              { name: "Polestar", flag: "SE" },
              { name: "Polonez", flag: "PL" },
              { name: "Pontiac", flag: "US" },
              { name: "Porsche", flag: "DE" },
              { name: "Praga", flag: "CZ" },
              { name: "Premier", flag: "IN" },
              { name: "Proton", flag: "MY" },
              { name: "Puch", flag: "AT" },
              { name: "Qoros", flag: "CN" },
              { name: "Qvale", flag: "IT" },
              { name: "Radical", flag: "GB" },
              { name: "RAM", flag: "US" },
              { name: "Rambler", flag: "US" },
              { name: "Ravon", flag: "UZ" },
              { name: "Reliant", flag: "GB" },
              { name: "Renault", flag: "FR" },
              { name: "Reo", flag: "US" },
              { name: "Rezvani", flag: "US" },
              { name: "Riley", flag: "GB" },
              { name: "Rimac", flag: "HR" },
              { name: "Rivian", flag: "US" },
              { name: "Roewe", flag: "CN" },
              { name: "Rolls-Royce", flag: "GB" },
              { name: "Ronart", flag: "GB" },
              { name: "Ropali", flag: "PH" },
              { name: "Rossion", flag: "US" },
              { name: "Rover", flag: "GB" },
              { name: "Ruf", flag: "DE" },
              { name: "Saab", flag: "SE" },
              { name: "SAIC", flag: "CN" },
              { name: "Saipa", flag: "IR" },
              { name: "Saleen", flag: "US" },
              { name: "Salmson", flag: "FR" },
              { name: "Samsung Motors", flag: "KR" },
              { name: "Saturn", flag: "US" },
              { name: "Scania", flag: "SE" },
              { name: "Scion", flag: "JP" },
              { name: "SEAT", flag: "ES" },
              { name: "Seres", flag: "CN" },
              { name: "Shanghai", flag: "CN" },
              { name: "Shelby", flag: "US" },
              { name: "Shuanghuan", flag: "CN" },
              { name: "Simca", flag: "FR" },
              { name: "Singer", flag: "GB" },
              { name: "Sipani", flag: "IN" },
              { name: "Sixt", flag: "DE" },
              { name: "Skoda", flag: "CZ" },
              { name: "Smart", flag: "DE" },
              { name: "Soueast", flag: "CN" },
              { name: "Spyker", flag: "NL" },
              { name: "SsangYong", flag: "KR" },
              { name: "SSC North America", flag: "US" },
              { name: "Standard", flag: "GB" },
              { name: "Steyr-Daimler-Puch", flag: "AT" },
              { name: "Studebaker", flag: "US" },
              { name: "Stutz", flag: "US" },
              { name: "Subaru", flag: "JP" },
              { name: "Sunbeam", flag: "GB" },
              { name: "Suzuki", flag: "JP" },
              { name: "Talbot", flag: "FR" },
              { name: "Tata", flag: "IN" },
              { name: "Tatra", flag: "CZ" },
              { name: "Tauro Sport Auto", flag: "ES" },
              { name: "Tesla", flag: "US" },
              { name: "Think", flag: "NO" },
              { name: "Tianma", flag: "CN" },
              { name: "Tofas", flag: "TR" },
              { name: "Toyota", flag: "JP" },
              { name: "Trabant", flag: "DE" },
              { name: "Tramontana", flag: "ES" },
              { name: "Triumph", flag: "GB" },
              { name: "Troller", flag: "BR" },
              { name: "Trulon", flag: "CN" },
              { name: "Tucker", flag: "US" },
              { name: "TVR", flag: "GB" },
              { name: "UAZ", flag: "RU" },
              { name: "Ultima", flag: "GB" },
              { name: "Unimog", flag: "DE" },
              { name: "Vandenbrink", flag: "NL" },
              { name: "Vauxhall", flag: "GB" },
              { name: "Vector", flag: "US" },
              { name: "Vencer", flag: "NL" },
              { name: "Venucia", flag: "CN" },
              { name: "Venturi", flag: "FR" },
              { name: "VinFast", flag: "VN" },
              { name: "Virago", flag: "GB" },
              { name: "Volkswagen", flag: "DE" },
              { name: "Volvo", flag: "SE" },
              { name: "Voyah", flag: "CN" },
              { name: "Wallyscar", flag: "TN" },
              { name: "Wanderer", flag: "DE" },
              { name: "Wartburg", flag: "DE" },
              { name: "Westfield", flag: "GB" },
              { name: "Wey", flag: "CN" },
              { name: "Wiesmann", flag: "DE" },
              { name: "Willys-Overland", flag: "US" },
              { name: "Wuling", flag: "CN" },
              { name: "XPeng", flag: "CN" },
      // FIX: Corrected "Xpeng" to "XPeng" for proper capitalization and branding.
      // { name: "Xpeng", flag: "CN" },
              { name: "Yamaha", flag: "JP" },
              { name: "Yulon", flag: "TW" },
              { name: "Zastava", flag: "RS" },
              { name: "ZAZ", flag: "UA" },
              { name: "Zeekr", flag: "CN" },
              { name: "Zenos", flag: "GB" },
              { name: "Zenvo", flag: "DK" },
              { name: "Zibar", flag: "IL" },
              { name: "Zotye", flag: "CN" },
              { name: "ZX Auto", flag: "CN" },
          ],
          "Motorcycles": "Motorcycles",
          "Bicycles": "Bicycles",
          "Boats": "Boats",
          "Spare Parts": "Spare Parts",
          "Accessories": "Accessories"
      },
      "RealEstate": ["Apartments", "Villas", "Offices", "Shops", "Lands", "Farms", "Buildings"],
      "Electronics": ["Phones", "Laptops", "Computers", "TVs", "Audio Systems", "Home Appliances", "Gaming Consoles"],
      "Furniture": ["Home Furniture", "Office Furniture", "Decor", "Outdoor Furniture"],
      "Fashion": ["Men’s Clothing", "Women’s Clothing", "Shoes", "Watches", "Accessories", "Jewelry", "Bags"],
      "Kids": ["Toys", "Baby Gear", "Kids Furniture", "Clothing", "Safety Tools"],
      "Pets": ["Dogs", "Cats", "Birds", "Fish", "Pet Accessories"]
    },
    "TourismAndHospitality": {
      "Hotels": ["Luxury", "Resorts", "Boutique", "Budget", "Eco", "Business"],
      "Rentals": ["Apartments", "Villas", "Cottages", "Farm Stays", "Glamping", "Boathouses"],
      "Transportation": ["Taxi", "Car Rentals", "Airport Shuttles", "Bike Rentals", "E-Scooters", "Boat Rentals"],
      "FoodAndBeverage": ["Restaurants", "Cafés", "Bars", "Lounges", "Delivery", "Street Food"],
      "Experiences": ["Tours", "Adventures", "Museums", "Events", "Shopping Tours", "Nature Trips"]
    },
    "HealthcareFacilities": {
      "Hospitals": ["General", "Children’s", "Maternity", "Rehabilitation", "Psychiatric", "Dental"],
      "Clinics": ["Family Medicine", "Cardiology", "Dermatology", "ENT", "Orthopedics", "Dental", "Physiotherapy", "Chiropractic"],
      "Pharmacies": ["Retail", "Hospital", "Online", "Specialty"],
      "TherapyCenters": ["Physical Therapy", "Occupational Therapy", "Speech Therapy", "Sports Rehab", "Pain Management"],
      "Diagnostics": ["Radiology", "Laboratories", "Ultrasound", "Genetic Testing"],
      "HomeHealth": ["Nursing", "Home Care", "Palliative Care", "Medical Equipment Rental"]
    },
    "EducationAndSeniorCare": {
      "Nurseries": ["Daycare", "Pre-School", "Kindergarten", "Childminders", "Crèche"],
      "Schools": ["Primary", "Secondary", "Private", "Vocational", "Technical", "Special Education"],
      "CollegesAndTraining": ["Universities", "Institutes", "Online Learning", "Professional Training", "Language Centers"],
      "SeniorCare": ["Retirement Homes", "Assisted Living", "Nursing Homes", "Memory Care", "Adult Daycare", "Hospice Care"]
    },
    "ProfessionalServices": {
      "Construction": ["Contractors", "Electricians", "Plumbers", "Carpenters", "Painters", "Welders"],
      "HomeServices": ["Cleaners", "Gardeners", "Pest Control", "HVAC Technicians"],
      "AutoServices": ["Mechanics", "Detailing", "Car Wash", "Towing"],
      "DesignAndCreative": ["Photographers", "Videographers", "Graphic Designers", "Printers", "Fashion Designers"],
      "Consulting": ["Lawyers", "Accountants", "Auditors", "Architects", "Interior Designers"],
      "Freelancers": ["Developers", "Writers", "Translators", "Marketers", "Virtual Assistants"],
      "BeautyAndPersonalCare": ["Hair Salons", "Barbers", "Makeup Artists", "Spas", "Massage Centers"]
    },
    "RetailAndShops": {
      "Supermarkets": ["Mini Markets", "Organic Stores", "Delis"],
      "FashionStores": ["Boutiques", "Shoe Shops", "Jewelry Stores"],
      "ElectronicsStores": ["Mobile Shops", "Computer Shops", "Home Appliance Stores"],
      "FurnitureStores": ["Home", "Office", "Outdoor"],
      "BookAndStationery": ["Bookstores", "Stationery Shops"],
      "PetStores": ["Pet Food", "Accessories", "Veterinary Supplies"],
      "Hardware": ["Tools", "Building Materials", "Electrical Supplies"]
    },
    "IndustrialAndManufacturing": {
      "Factories": ["Textiles", "Food & Beverage", "Plastics", "Chemicals", "Construction Materials"],
      "Workshops": ["Metalwork", "Woodwork", "Glasswork", "Printing & Packaging"],
      "RenewableEnergy": ["Solar Panels", "Wind Systems", "Energy Storage"],
      "IndustrialSupplies": ["Machinery", "Tools", "Safety Equipment"]
    },
    "LogisticsAndDelivery": {
      "Transport": ["Trucking", "Cargo", "Freight"],
      "CourierServices": ["Delivery", "Postal", "Express"],
      "Storage": ["Warehousing", "Cold Storage", "Distribution Centers"],
      "Movers": ["Home Movers", "Office Relocation", "Packing Services"]
    },
    "FinanceAndAdministration": {
      "FinancialInstitutions": ["Banks", "Insurance", "Exchanges", "Microfinance"],
      "ConsultingAndHR": ["Recruitment Agencies", "Business Consultants", "Auditing Firms"],
      "Government": ["Municipal Services", "Embassies", "Public Offices"]
    },
    "AgricultureAndEnvironment": {
      "Farms": ["Livestock", "Poultry", "Dairy", "Beekeeping"],
      "Crops": ["Vegetables", "Fruits", "Grains"],
      "Supplies": ["Fertilizers", "Seeds", "Irrigation", "Machinery"],
      "EcoProjects": ["Recycling", "Sustainability", "Landscaping"]
    },
    "TechnologyAndInnovation": {
      "ITServices": ["Web Development", "App Development", "Software Solutions", "Cloud Hosting"],
      "HardwareRepair": ["Phone Repair", "Computer Repair", "Electronics Maintenance"],
      "TechStartups": ["AI", "Robotics", "IoT", "Blockchain", "Cybersecurity"]
    },
    "CommunityAndSocial": {
      "Organizations": ["NGOs", "Charities", "Clubs", "Volunteer Groups"],
      "ReligiousCenters": ["Churches", "Mosques", "Temples"],
      "CulturalCenters": ["Museums", "Libraries", "Theaters"],
      "EnvironmentalInitiatives": ["Animal Shelters", "Tree Planting", "Clean-Up Projects"]
    }
};

// FIX: Replaced JSX syntax with React.createElement to resolve type errors in a .ts file.
// JSX syntax is not supported in .ts files by default and requires a .tsx file extension.
export const getCategoryIcon = (categoryName: string): React.ReactElement => {
    const normalizedName = categoryName.toLowerCase().replace(/\s*&\s*/, 'and');
    switch (normalizedName) {
        // Top Level
        case 'marketplaces': return React.createElement(MarketplaceIcon);
        case 'tourismandhospitality': return React.createElement(TourismIcon);
        case 'healthcarefacilities': return React.createElement(HealthcareIcon);
        case 'educationandseniorcare': return React.createElement(EducationIcon);
        case 'professionalservices': return React.createElement(ServicesIcon);
        case 'retailandshops': return React.createElement(RetailIcon);

        // Sub Level
        case 'electronics': return React.createElement(ElectronicsIcon);
        case 'vehicles': return React.createElement(CarIcon);
        case 'realestate': return React.createElement(HouseIcon);
        case 'fashion': return React.createElement(FashionIcon);
        case 'homeandgarden': return React.createElement(PlantIcon);
        case 'hobbies': return React.createElement(HobbiesIcon);
        default: return React.createElement(DefaultCategoryIcon);
    }
};

export const getCategoryCount = (category: any): number => {
    if (Array.isArray(category)) {
        return category.length;
    }
    if (typeof category === 'object' && category !== null) {
        return Object.keys(category).length;
    }
    return 0;
};
